name: revity

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  geolocator: ^10.1.0
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
